// Currency + country/dial-code data used across the app.

export const CURRENCIES: { code: string; name: string; symbol: string }[] = [
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "EGP", name: "Egyptian Pound", symbol: "E£" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs" },
  { code: "MXN", name: "Mexican Peso", symbol: "Mex$" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "QAR", name: "Qatari Riyal", symbol: "ر.ق" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "SAR", name: "Saudi Riyal", symbol: "ر.س" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
];

export const DEFAULT_CURRENCY = "INR";

export function formatMoney(amount: number | null | undefined, currency = DEFAULT_CURRENCY) {
  if (amount === null || amount === undefined) return "—";
  try {
    return new Intl.NumberFormat(currency === "INR" ? "en-IN" : "en-US", {
      style: "currency",
      currency,
      maximumFractionDigits: 0,
    }).format(amount);
  } catch {
    return `${currency} ${amount.toLocaleString()}`;
  }
}

export const COUNTRY_CODES: { code: string; dial: string; name: string }[] = [
  { code: "IN", dial: "+91", name: "India" },
  { code: "US", dial: "+1", name: "United States" },
  { code: "GB", dial: "+44", name: "United Kingdom" },
  { code: "AE", dial: "+971", name: "United Arab Emirates" },
  { code: "AR", dial: "+54", name: "Argentina" },
  { code: "AU", dial: "+61", name: "Australia" },
  { code: "BD", dial: "+880", name: "Bangladesh" },
  { code: "BE", dial: "+32", name: "Belgium" },
  { code: "BR", dial: "+55", name: "Brazil" },
  { code: "CA", dial: "+1", name: "Canada" },
  { code: "CH", dial: "+41", name: "Switzerland" },
  { code: "CL", dial: "+56", name: "Chile" },
  { code: "CN", dial: "+86", name: "China" },
  { code: "CO", dial: "+57", name: "Colombia" },
  { code: "DE", dial: "+49", name: "Germany" },
  { code: "DK", dial: "+45", name: "Denmark" },
  { code: "EG", dial: "+20", name: "Egypt" },
  { code: "ES", dial: "+34", name: "Spain" },
  { code: "FI", dial: "+358", name: "Finland" },
  { code: "FR", dial: "+33", name: "France" },
  { code: "HK", dial: "+852", name: "Hong Kong" },
  { code: "ID", dial: "+62", name: "Indonesia" },
  { code: "IE", dial: "+353", name: "Ireland" },
  { code: "IL", dial: "+972", name: "Israel" },
  { code: "IT", dial: "+39", name: "Italy" },
  { code: "JP", dial: "+81", name: "Japan" },
  { code: "KE", dial: "+254", name: "Kenya" },
  { code: "KR", dial: "+82", name: "South Korea" },
  { code: "LK", dial: "+94", name: "Sri Lanka" },
  { code: "MX", dial: "+52", name: "Mexico" },
  { code: "MY", dial: "+60", name: "Malaysia" },
  { code: "NG", dial: "+234", name: "Nigeria" },
  { code: "NL", dial: "+31", name: "Netherlands" },
  { code: "NO", dial: "+47", name: "Norway" },
  { code: "NP", dial: "+977", name: "Nepal" },
  { code: "NZ", dial: "+64", name: "New Zealand" },
  { code: "PH", dial: "+63", name: "Philippines" },
  { code: "PK", dial: "+92", name: "Pakistan" },
  { code: "PL", dial: "+48", name: "Poland" },
  { code: "PT", dial: "+351", name: "Portugal" },
  { code: "QA", dial: "+974", name: "Qatar" },
  { code: "RU", dial: "+7", name: "Russia" },
  { code: "SA", dial: "+966", name: "Saudi Arabia" },
  { code: "SE", dial: "+46", name: "Sweden" },
  { code: "SG", dial: "+65", name: "Singapore" },
  { code: "TH", dial: "+66", name: "Thailand" },
  { code: "TR", dial: "+90", name: "Turkey" },
  { code: "TW", dial: "+886", name: "Taiwan" },
  { code: "VN", dial: "+84", name: "Vietnam" },
  { code: "ZA", dial: "+27", name: "South Africa" },
];

export const LEAD_SOURCES = [
  "Referral",
  "Website",
  "Cold Call",
  "Cold Email",
  "LinkedIn",
  "Event / Conference",
  "Paid Ads",
  "Partner",
  "Other",
];
