project_id = "sipwkfklkszedqmbhqac"

[functions.sales-agent]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.contact-support]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false
